name: Deploy to cPanel

on:
  push:
    branches:
      - main

jobs:
  ssh-deploy:
    name: SSH Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via git pull over SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd ~/suvo.dev
            git fetch origin main
            git reset --hard origin/main
